### PR TITLE
fix NullPointer exception while using sonarqube 5.2

### PR DESCRIPTION
**Pull request by bdbogjoe**

### CODE REVIEW

**Comment by omayevskiy** [comment]
Hello, thx for your pull request.
I cannot accept it because it adds dependency on plugin: 'org.jetbrains.intellij', which downloads 222 MB intellij sources.
You also moved META-INF to src/main/resources, this is correct to do so if you build the project with gradle.

But I do not build the plugin with gradle. Gradle is only used to generated the idea's project files and manage the dependencies. The plugin is built and deployed using intellij's built in features and not by gradle!

- Please remove plugin: 'org.jetbrains.intellij'
- move back META-INF

Thank you!

**Comment by bdbogjoe** [comment]
Ok will move it back but how to build this plugin without gradle ?

**Comment by omayevskiy** [comment]
With intellij like any hello world plugin!
Build -> Prepare Plugin Module 'sonar-intellij-plugin' For Deployment

**Comment by bdbogjoe** [comment]
should be ok now

**Comment by bdbogjoe** [comment]
according to me better to have standalone build without any requirement to have IntelliJ to build plugin, but it is as you want you are the owner :smirk:

**Comment by omayevskiy** [comment]
I agree, especially if you want to build on ci. But this is not what you wanted to fix in first place, also I am the only developer ;-)

**Comment by bdbogjoe** [comment]
yes you are right, i mixed 2 issues

**Comment by omayevskiy** [comment]
released 2.0.10

**Pull request merged**
