### PR TITLE
Solution proposal for #177 - implement compatibility with IDEA v.2017.1

### PR DESCRIPTION
**Pull request by oleynik**

### CODE REVIEW

**Comment by mcmahonjohn** [comment]
@omayevskiy Can this PR get reviewed?

**Comment by Stargator** [comment]
@omayevskiy Are you still active?

**Comment by dagwud** [comment]
@omayevskiy / @aheusingfeld / @jibidus ... please would you consider this PR? A nice simple version-number fix to enable the plugin in newer versions of IntelliJ.

**Comment by omayevskiy** [comment]
uploaded version 2.1.2

**Pull request merged**
