### PR TITLE
Added Organization field which is needed in case of integration with Sonarcloud.io

### PR DESCRIPTION
**Pull request by bonivan**
Without Organization provided plugin is unable to download list of projects available for specified user in Sonarcloud.io.
If user in Sonarcloud was created from Github then name for organization would be <GitHub username>-github

### CODE REVIEW

**Comment by omayevskiy** [comment]
what I did:
added SonarQube server with
name: sonarcloud
host url: https://sonarcloud.io
organization: sonar-intellij-plugin
anonymous: yes

next OK
next Apply

on SonarQube resources clicked Add (+)
next Download Resources

following error occurred:
Bildschirmfoto 2019-08-02 um 16 27 24

**Comment by bonivan** [comment]
I had to increase version of sonar-ws dependency to 6.7 to be able to work with Sonarcloud's version of components API. The issue is that this version of sonar-ws is not compatible with Sonar servers that use earlier version of components API since version 6.7 uses parameter "component" in REST call while older version use "componentId" and/or "componentKey". Increasing version of sonar-ws might be a big deal so if you decide not to do it then please close this request without merging.

**Comment by omayevskiy** [comment]
hi @bonivan 
I tested with sonarcloud.io
can u confirm u can connect the plugin with sonarcloud, download resources and issues?

**Comment by bonivan** [comment]
Yes, I was able to connect to Sonarcloud using token and load projects (and no exceptions happened during loading of modules) and issues.

**Comment by omayevskiy** [comment]
>Yes, I was able to connect to Sonarcloud using token 
ok, I did not use token, will try again

**Comment by omayevskiy** [comment]
tested with token, got same error 400 "The component parameter is missing" :-/

using
IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 23, 2019
Runtime version: 1.8.0_121-b13 x86_64
VM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
macOS 10.14.6
GC: PS Scavenge, PS MarkSweep
Memory: 500M
Cores: 8
Registry: java.completion.argument.hints.internal=false
Non-Bundled Plugins: org.mayevskiy.intellij.sonar

https://sonarcloud.io
with plugin's token

**Comment by omayevskiy** [comment]
I guess I did not pull the newest state from your fork.
seems it works now 👍

**Pull request merged**
