### PR TITLE
use gradle to build plugin

### PR DESCRIPTION
**Pull request by bdbogjoe**

### CODE REVIEW

**Comment by omayevskiy** [comment]
This makes it possible to build with gradle, if you build it by: ```gradle build```
but how do you start the plugin in intellij?
after doing
```gradle idea```
and executing run-sonar-plugin run configuration inside Intellij
I cannot see the plugin any more in the started idea instance.

**Comment by bdbogjoe** [comment]
You can run with : gradle runIdea


See : https://github.com/JetBrains/gradle-intellij-plugin/

To run inside current idea did not check yet

**Comment by omayevskiy** [comment]
yes I read it just after writing the posting.
This changes the way I was working with the plugin
There are a couple more things to check:
 - how to debug?
 - check if produced zip file is the same as before
 - make use of publishing

**Comment by bdbogjoe** [comment]
one nice feature is to set version in build.gradle, and the plugin.xml is updated during the build

for debugging it is even easier, run setup gradle run command in Intellij with runIdea task, and start debug

I just tried, works fine

**Pull request merged**
