### PR TITLE
Fix query limitation in GetAllProjects in SonarServer.java

### PR DESCRIPTION
**Pull request by DancZer**
Set pageSize to 10000 for project query to receive all project not only the top 100.

### CODE REVIEW

**Comment by djas19** [comment]
This change breaks the retrieval of our project:

`org.sonarqube.ws.client.HttpException: Error 400 on https://our.project.be/api/components/search?qualifiers=TRK&ps=10000 : {"errors":[{"msg":"'ps' value (10000) must be less than 500"}]}
	at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:36)
	at org.sonarqube.ws.client.BaseService.call(BaseService.java:55)
	at org.sonarqube.ws.client.BaseService.call(BaseService.java:50)
	at org.sonarqube.ws.client.component.ComponentsService.search(ComponentsService.java:58)
	at org.intellij.sonar.sonarserver.SonarServer.getAllProjects(SonarServer.java:146)
	at org.intellij.sonar.sonarserver.SonarServer.getAllProjectsAndModules(SonarServer.java:118)
	at org.intellij.sonar.configuration.ResourcesSelectionConfigurable$DownloadResourcesRunnable.run(ResourcesSelectionConfigurable.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:574)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by DancZer** [comment]
It says "value (10000) must be less than 500". Is it configurable? Maybe if we would query this option value and we would use that would be a better solution. But I'm not really into it, to do it. For us the 500 sufficient.

**Comment by DancZer** [comment]
Or we can use the paging.

**Comment by djas19** [comment]
I do not find the option to increase the page size anywhere on the server. 500 would be more than enough for us too.

**Pull request merged**
